version: "3"
services:
  cache:
    container_name: redisstock
    image: "redis"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime:ro
  auth:
    build: ./main-server
    container_name: main-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - cache